// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cinemas": {
            "get": {
                "description": "Displays a list of cinemas with pagination and search features by city.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cinemas"
                ],
                "summary": "Get Cinema list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by city",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Amount of data per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_pkg_response.SuccessResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Saving new cinema data to database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cinemas"
                ],
                "parameters": [
                    {
                        "description": "Data Cinema",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_usecase.CreateCinemaInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Cinema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Cinema": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "screens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Screen"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Screen": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "cinema": {
                    "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Cinema"
                },
                "cinemaID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "hasDolby": {
                    "type": "boolean"
                },
                "hasIMAX": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "screenType": {
                    "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.ScreenType"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Seat"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_internal_cinema_domain.ScreenType": {
            "type": "string",
            "enum": [
                "regular",
                "vip",
                "imax"
            ],
            "x-enum-varnames": [
                "ScreenTypeRegular",
                "ScreenTypeVIP",
                "ScreenTypeIMAX"
            ]
        },
        "github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Seat": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "row": {
                    "type": "string"
                },
                "screen": {
                    "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.Screen"
                },
                "screenID": {
                    "type": "string"
                },
                "seatType": {
                    "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_internal_cinema_domain.SeatType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_internal_cinema_domain.SeatType": {
            "type": "string",
            "enum": [
                "regular",
                "premium",
                "vip"
            ],
            "x-enum-varnames": [
                "SeatTypeRegular",
                "SeatTypePremium",
                "SeatTypeVIP"
            ]
        },
        "github_com_dharmasaputraa_cinema-api_internal_cinema_usecase.CreateCinemaInput": {
            "type": "object",
            "required": [
                "address",
                "city",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_pkg_response.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_pkg_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_pkg_response.ErrorDetail"
                    }
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_pkg_response.Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_dharmasaputraa_cinema-api_pkg_response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/github_com_dharmasaputraa_cinema-api_pkg_response.Meta"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Cinema API",
	Description:      "This is the API documentation for the Cinema management system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
